language: node_js
node_js:
- '7'
after_success:
- npm run coverage
notifications:
  slack:
    secure: gsdCtzC9ZXNzN1cXW411ykTs9H8nQywdFhFKfWK1DqOJ97FUNUbQpkcLg+ppfWy3tbTt2w32t8jrPMvQ+VT8qie3eOSjMrxZqMp42YJqukg1O4hwedU/xJBEUAqsDzRboC/WiAGug1a7cHGOOyR9QJVU4EXwVYqb1WoZkp3P5+GAVpNd3H5Y5PQNjuIzPYlffauk43qGFAYaMgVl6z/Qq9F09z5IfZJOWBgHRE49qucZ9BvT7fhfPqbTKIB7fFtVWF+22mVL/bdmvEcmT6hxbaGITIsW6BPy1xVNQzH1slJXu3LZLgT7rsO83fDVAu0RlHRsV+3IqIM3wJFsAfL0LEUv5GMaZEO/0jADUWjwiClLmQq6m2lu5tbC5zSq/YHq9B59Axzd1XJjfowTEr8JaEynizZJztv+DbD1RoZQjTmF5mGnpHefkdvtME4DOZpXTPit+0SLxZQvFs9IF3ZAV5wUlw/O8nvhV8P2T+9VltoU2lAa7taaRyCbzBZsdlYUnNjWDhRGlimhaZzmSMkNbJ7E5RBj7VpXsMeespKXTsji1NLJy3X8p6/PR/04k3j0EtlOyPJ202ornCGg09MJLTbPGA1m0VhFIYgercmz7xBQW6snOqdgWYNKXWDtk8t/pZfn03H1FJ3AdyvdTR4PdDIadCbRj27fJ3uV6U8rI6c=
